# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-18 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=40)),
                ('uemail', models.CharField(max_length=30)),
                ('ureceiver', models.CharField(max_length=10)),
                ('uaddress', models.CharField(max_length=50)),
                ('uphone', models.CharField(max_length=11)),
                ('upostcode', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
    ]
